list_services:
  chanki:
    service: yocha
    once: true
    role:
      owner: "O"
    auth:
      - 'phone'
      - 'email'
    webhook:
      token_revoked: '23432542436345'
  yocha:
    service: yocha
    once: true
    role:
      owner: "O"
      admin: "A"
      user: "U"
      guest: "G"
    auth:
      - 'phone'
      - 'email'
  vector:
    service: di
name_app:
  anubis
short_jwt:
  true

