
services:

  mongodb_anubis_server:
    image: mongo:latest
    container_name: mongodb_anubis
    restart: always
    env_file: config_server.env

    ports:
      - 27118:27017
    volumes:
      - ./.data_bd:/data/db
      - ./.data_bd/dev.archive:/Databases/dev.archive
      - ./.data_bd/production:/Databases/production
    networks:
      - mongodb_anubis_network

networks:
  mongodb_anubis_network:
    driver: bridge